### ISSUE TITLE
Compiler error in connection with LovyanGFX.

### ISSUE THREAD

**Issue by zsoltturcsan** [SubCoderHUN/WT32-SC01-PLUS#2]
Hi,

I found compiling errors in connection with LovyanGFX.
Do you have any idea/solution for this?

Many thanks in advance!

[{
	"resource": "/c:/Users/tzs/Desktop/GitHub/WT32-SC01-PLUS/WT32-SC01-PLUS/.pio/libdeps/wt32-sc01-plus/LovyanGFX/src/lgfx/v1/platforms/esp32/Bus_SPI.cpp",
	"owner": "cpp",
	"severity": 8,
	"message": "'gpio_matrix_out' was not declared in this scope; did you mean 'gpio_iomux_out'?",
	"startLineNumber": 181,
	"startColumn": 5,
	"endLineNumber": 181,
	"endColumn": 5
}]

[{
	"resource": "/c:/Users/tzs/Desktop/GitHub/WT32-SC01-PLUS/WT32-SC01-PLUS/.pio/libdeps/wt32-sc01-plus/LovyanGFX/src/lgfx/v1/platforms/esp32/Light_PWM.cpp",
	"owner": "cpp",
	"severity": 8,
	"message": "'ledcSetup' was not declared in this scope",
	"startLineNumber": 40,
	"startColumn": 5,
	"endLineNumber": 40,
	"endColumn": 5
},{
	"resource": "/c:/Users/tzs/Desktop/GitHub/WT32-SC01-PLUS/WT32-SC01-PLUS/.pio/libdeps/wt32-sc01-plus/LovyanGFX/src/lgfx/v1/platforms/esp32/Light_PWM.cpp",
	"owner": "cpp",
	"severity": 8,
	"message": "'ledcAttachPin' was not declared in this scope; did you mean 'ledcAttach'?",
	"startLineNumber": 41,
	"startColumn": 5,
	"endLineNumber": 41,
	"endColumn": 5
}]

**Comment by SubCoderHUN** [comment]
Hello! 😄
Thank you for your feedback! 🙇

This is a strange error log.
Have you tried re-download the LovyanGFX library?

**Comment by zsoltturcsan** [comment]
Hello!

Thanks for the info, full fresh install solved it!
