### ISSUE TITLE
Can't compile under certain condition.

### ISSUE THREAD

**Issue by Dzsonzii** [SubCoderHUN/WT32-SC01-PLUS#4]
Not really an issue, just a heads up: If you have unpacked the code to a folder which has space or special characters in the name, platformio just won't be able to build the project. I don't know if it's a platformio or program issue, I just wanted to give a headsup.

**Comment by SubCoderHUN** [comment]
Hello! 😄
Thank you for your feedback! 🙇

I think that's an issue for platformio.
VS Code in general can handle spaces in folder names, for special characters im not sure.

Thanks! 🤗
